オブジェクト指向版ボウリングスコア計算プログラムを作成しました
junohm410/ruby-practices pull request #10
Opened 2023-09-17 03:10 UTC by junohm410

プラクティスの課題として、オブジェクト指向版ボウリングスコア計算プログラムを作成しました。
レビューのほど、何卒よろしくお願いいたします🙏

2023-09-23 15:11 UTC, u1tnk requested changes
大体良いですね 👍 

変数名の整理と、
Xを判定している箇所が3つあるので一箇所にしましょう。Xを判定する責務はどこなのかを考えてその一箇所にましょう。

2023-09-23 15:11 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +    [first_shot, second_shot].sum(&:score) == 10
これはストライクのときにもtrueを返してしまうのでメソッド名と内容が違うのが良くないです。
気づかずに処理の順番をかえるとバグになることもあります。

2023-09-23 15:11 UTC, u1tnk commented on 06.bowling_object/game.rb
> +  FRAME_BEFORE_FINAL = 9
ちょっと定数が多いので整理して欲しいです。

例えばBEFOREのものであれば `FINAL_FRAME = 10` とあれば  `FINAL_FRAME  - 1` とあれば一つ前なのは分かりますし、indexとして使う場合も `frames[FINAL_FRAME - 1]` とあればrubyの基礎がわかれば最後のフレームのデータが欲しいとわかります。

2023-09-23 15:11 UTC, u1tnk commented on 06.bowling_object/game.rb
> +    pinfalls = pinfall_string.split(',')
配列を変数に入れるときは変数名を複数形にしましょう。
慣習(少なくともruby界隈では)です。

2023-09-23 15:11 UTC, u1tnk commented on 06.bowling_object/game.rb
> +  FRAME_BEFORE_FINAL_IDX = 8
[プログラミング初心者は変数名やメソッド名を略さない方がいいよ、という話 - give IT a try](https://blog.jnito.com/entry/2020/10/20/092724)

idxはちょっと中途半端かと思います。

ちなみに数行のブロックであれば `i` を慣習的に使い

2023-09-25 01:10 UTC, junohm410 commented on 06.bowling_object/game.rb
> +  end
Xを判定することは「Xというスコアを『1投目にピン10本を倒して終了したフレーム』とみなして1フレームとして切り分ける」という仕事なので、`Game`クラスが結果の文字列を分割する際に行う責務と考えました。
よって、`organize_same_frame_pinfalls`というプライベートメソッドにその切り分けの仕事を分割させる形で修正しました。

ただ、このメソッドが`same_frame_pins`を破壊的に変更するメソッドになっており、もしかしたらこれがよくないかなとも思っております……。
とはいえ、`same_frame_pins`を毎ループでリセットさせずに使う必要があり、このような形になっています。
このあたり、もし良くない点やアドバイスがあればご教示いただけるとありがたいです。
どうぞよろしくお願いいたします🙏

2023-09-25 01:14 UTC, junohm410 commented
レビュー、ありがとうございました🙏
ご指摘いただいた点、すべて修正対応いたしました。
Xの判定の修正の部分で、補足コメントをさせていただきました。

ご確認のほど、何卒よろしくおねがいいたします🙇‍♂️

2023-09-25 16:17 UTC, u1tnk requested changes
大枠基本的に問題無いですし、責務の分割もおかしくは無いのですが、判断の結果が全てGameになったせいでGameクラスだけが肥大化しています。

Gameクラスを分割して欲しいのですが、ちょっと難しいと思うので方針だけ書きます。
インプットの文字列から framesにする処理を Frameクラスのクラスメソッドに移動してみましょう。

2023-09-25 16:17 UTC, u1tnk commented on 06.bowling_object/shot.rb
> +  attr_reader :fallen_pin
scoreメソッドがあればこれは必要無いはずです。

2023-09-25 16:17 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +    [first_shot, second_shot, @third_shot].sum(&:score)
[細かい話なのでそのままでも良いです]
大差は無いのですが、そのまま使うのであれば内部ではインスタンス変数を使った方が内部のデータと明示できると思っていますし、ここはthirdがインスタンス変数なのであわせた方が良いかと思います。

2023-09-25 16:17 UTC, u1tnk commented on 06.bowling_object/game.rb
> +  end
> Xを判定することは「Xというスコアを『1投目にピン10本を倒して終了したフレーム』とみなして1フレームとして切り分ける」という仕事なので、Gameクラスが結果の文字列を分割する際に行う責務と考えました。

そうですね Gameで分けるときに使うかShotにするかのどちらかと思うのでそれで大丈夫です。

> ただ、このメソッドがsame_frame_pinsを破壊的に変更するメソッドになっており、もしかしたらこれがよくないかなとも思っております……。

破壊的という言葉の定義にもよりますが、一時配列に追加していくだけのものはそんなに問題無いですね。
同じ配列などを何度も変更したりすると、変数名と乖離するし、場所によって内容が変わるのでよくないですが、この場合は `same_frame_pins` という意味は変わらず、だんだん完成するだけなので。

2023-09-25 16:17 UTC, u1tnk commented on 06.bowling_object/game.rb
> +  def organize_same_frame_pins(fallen_pin, same_frame_pins, current_frame)
こちらの引数の配列に破壊的な追加をする方がちょっと良くないですね。
返り値でどうにかしましょう。

2023-09-26 10:57 UTC, junohm410 commented on 06.bowling_object/frame.rb
> +    [first_shot, second_shot, @third_shot].sum(&:score)
内部でのゲッターメソッドとインスタンス変数の参照についての考え方について、大変参考になりました🙏ありがとうございます！修正いたしました。

2023-09-26 11:21 UTC, junohm410 commented on 06.bowling_object/frame.rb
> +      same_frame_pins += Frame.collect_pin(fallen_pin, current_frame)
`same_frame_pins`に要素を追加していく方法について、条件分岐によって追加要素が1or2個になり、2個の場合には`<<`による追加ができないためかなり悩みました。

最終的に、追加要素が1or2個のどちらであっても配列で戻り値を得るようにして、配列の`+`メソッドで追加するようにしました。
1個の場合でも配列に格納するのがちょっと気持ちわるいとは思ったのですが、現時点ではこれが精一杯でした……🙇‍♂️

この点含め、ご指摘点あれば教えていただけますと幸いです🙏

2023-09-26 11:22 UTC, junohm410 commented
レビューいただき、ありがとうございました🙏
ご指摘いただいた点、修正いたしました。
悩んだ点・考えた点はコメントしております。

ご確認のほど、何卒よろしくお願いいたします🙏

2023-09-26 11:26 UTC, junohm410 commented
レビューいただき、ありがとうございました🙏
ご指摘いただいた点、修正いたしました。
悩んだ点・考えた点はコメントしております。

ご確認のほど、何卒よろしくお願いいたします🙏

2023-09-26 15:20 UTC, u1tnk approved these changes

2023-09-26 15:20 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +      same_frame_pins += Frame.collect_pin(fallen_pin, current_frame)
返り値の型はrubyでは可変ですが、合わせた方が良いので両方配列の今の形で良いと思いますよ 👍

2023-09-26 15:20 UTC, u1tnk commented on 06.bowling_object/frame.rb
> +      same_frame_pins += Frame.collect_pin(fallen_pin, current_frame)
細かい事を言うと クラスメソッド同士なら Frameをつけなくても呼べると思います。
修正するほどでは無いです。

2023-09-27 02:48 UTC, junohm410 commented on 06.bowling_object/frame.rb
> +      same_frame_pins += Frame.collect_pin(fallen_pin, current_frame)
コメントありがとうございました🙏同じクラスメソッド同士であればクラス名をつけなくてもクラスメソッドを呼べること、手元で確認しました。勉強になりました🙏

2023-09-27 02:48 UTC, merged